### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Ifycode** [jnsjknn/nettikamu#3]
Hi @jnsjknn, this is [@Ifycode](https://github.com/Ifycode) from [Code Collabo](https://github.com/code-collabo). Sorry about sending an issue. I couldn't find an email or social media account to send my message to on your profile. 
You had already deleted your fork before I was able to give you this message/feedback, so I didn't know if you'd get the notification.

Your [feedback](https://github.com/code-collabo/node-mongo-cli/pull/37#issuecomment-800511369) was helpful to reconstructing the [contributing to the node-mongo-cli](https://github.com/code-collabo/node-mongo-cli) section of the readme. 

You can check it out if you still have interest in contributing to the project. Sorry for the inconvenience caused by my (previously) not well written readme. 

Thank you for your patience.

**Comment by jnsjknn** [comment]
There is an email address and a link to my Instagram on my [profile](https://github.com/jnsjknn/jnsjknn)

Closing this issue as it's completely unrelated to nettikamu
